openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'plantbot'
  description: Poll sensors for what your plant is feeling

paths:
  /api/sensors:
    get:
      summary: Sensor Data object
      responses:
        '200':
          description: Successfully sent sensor data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorData'
        404:
          description: No sensors reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Date:
      description: Time of sensors polled
      type: string
    SensorData:
      type: object
      required:
        - date
        - name
        - type
        - value
      properties:
        date:
          $ref: '#/components/schemas/Date'
        name:
          type: string
        type:
          type: string
          enum:
            - humidity
            - temp
            - light
            - weight
            - moisture
        value:
          type: number
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []